apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tailscale-sealed-secret.yaml
  - tailscale-helmrelease.yaml
  - tailscale-values.yaml
  - node-ssh-service.yaml
