---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCmczDFpq+iRGlYPkWr6tLcOiIIRbAnERf6OpBVjFXJUEtozQ8hQ3BJ8fMYzkQZdL+XWSsx4uwuN53xnAKnxNYyd5q2Fv0bZdQJaxhInsXyet+stf8LUAgJgHYM8CY+f+y6TSKxGE8BisS99VChREx4kdg8cefFP+6ebbMxkOZSn9dIgBup9XusVyjgRwYeStMrd2eOMV+o50g/CI/LaTiGaDQIwCn+DRdeYP6yk5zeTccnZ2iNGMDJAClamIoLvS1nYYnQT3MZj87jydLeI9kBGnG/9IqVY/tf46d0ykB/ltrVZTLQ45FVfGxWQZmOjec2bHpAfv2gcpsw7Gt0wegBjdXw1KrEeORjBjHsl8QLLU9CfMQzYyAm7UkUTx9rjjrQKxR0NS3GCJpt8F5YVxEenzX4aK0EFhXMH5yOijzn7on5wyHra6m+X7Fsj4/7gd9XVnLd7n+lWzeXqPtIxYgGwakFDmbJYs7Xe98qRdNFo7S3l3nMeUoqHaCgaQl+s2wyne+81DUsr0t1O1rcMUgUwNEFw9IkspqYR3x2Y2RgCvg3JXnu6ShIohmGYurbmt3tVoTkc2pMp7vbaN90bTd0U3aIh1Y2+p73R5ZEVmgCPH362fH7cOMhYBxaTxNAUVC0+swYibliBPbQ6L90O56E8OfQFAIc19dSHqZE9OBvPTYCFE1NSiDTCNxfnyokabm1MTZyDLXRK1MA5w+aYCd5+w==
    client_secret: AgA6d4a1yeLixXBh3sLUql9CFOiC/ByxVWa3TSg/yhBKCbDoNQPngdVLvfWDvY0hE8xi6GHYVOwfrHanq3rpTVBP0ExfiX0L5dio57lpeHmOP6gx3RFa0fDkholW5eyubnnXAASiocamCVuz+NCdHt8ZY4G94F8vKMFEA0QHqnDXwGkiw3tzWyZl/nFLfVPvZ8XAaxRTpu9Sjzf2f55sMFlK75wwE3Tc1ftzlfFJTAL2gjtGFX5yDMaOHJ9yqIB6XGnSDhups4lxKVJTWav7p8YfJhIzedWzRHC75psMT6xpEfhedFb+oUN4zO0HiOXixIrZM1JPKdFKiKME2iH76vIH1raZZYn88rp5QcrGiJkFAeOStePVfOEc2/UfCFH229LeFsBL0YxB6kr/Ue8T0QyKs2daE17nasUreSaflt1zrRa+UkPrALQgSN7Y0xWK4y+b10d06p9Dj0dewwMmskMQgZxvioHoLdd7Yc3Z67DWPA17+YBVAEpLCEDR37520gA5CG1Y9U54wEqDuXCTgOiLDGh2Yj12yPx7sGBUp9BmJBGCJr0AZpvGPhfjkcx4E4TAnsMGUPGaw47/PNm3ZuZZSvrIhAhOnHaEbaq7W4Pw9fT5SA3sd4IbWkSjUYsNz/Y4gmSra4q0nlunV5T7nI3PQHWtn74OXkpxU/yalsr1lpDjF1TDhQ5RaA79xlJJntS7K9R8ZfzdLT5pvcON6MJ4frEUDdpT5ZxDfujAxQG4XiGbwzAuz50YKgwL5Nr333/X0datg0JY+p0WtcNJ1QaC
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-oauth
      namespace: tailscale
