---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner-secret
  namespace: act-runner
spec:
  encryptedData:
    REGISTRATION_TOKEN: AgBg1YRxjwCZ/0genkLH8Z9ZXIZhIHxtwzzKIqyB2UUpLoF426xTH5cILkiRmytPmGi9oDlhtzjPLASuQYzef1053apLKhg/sW2W60aRM1NTJCkvEJzn19DycIjL3MlTX+71zGrxaLT4kg0LCE6g4YoDXLNxnGGd9Lm9L2djT6J+3Xm3GxvK6cWKvTd1v1C0+77KiTIadBNW3gVheF+NBuQafuonppiAyJpx6W/EXLhgduAT+wHXnaaNEE2QdU07qHaTVsjw5tSJdcVZ5cQQcCq7K7EDOx7sJ1lwGmX0eE9ixwPivGAdo8+lcua7zQZi6TDa36Vdo8fnnHL/lMRMZEEKJz83+payOaYEFnS+jNX4NWJDWEWjydt/S+Ewy25TivIw/oUVmDwqWZSiGDs1mo8jUhYjO2wZrS9yG99HrwSn2bbxelfCnMqYt4/bVX5FWbbJgUZH7DvOLKcIJUGSvYyO56bM6PjE25wVzeVLLijjuI8BgehfuX2D5IGv3ZDBcmvVymaFPrQYv9/RCebPKyXx03Pj4av7OWxvmfVxmUulzDnF7G3ZII1KLtLs1caTEPD/TS48BWX9rsEVwnK4iyq8dQ0ZA5Q1aC8kWRPfPUYPpG5bUabTOE9HstOKPTPR8EY4NLJ4V/060qp0V0RZYKBEmZABbIyR3XBG4avPG3vd5FhKeCF2c8A+2XO39LWbh02zafT3Ydq6pM6jpXUHx4rJA7OuIh4PzId4bj1wGiIJ9YQJnwgVmeN1bsB/
  template:
    metadata:
      creationTimestamp: null
      name: act-runner-secret
      namespace: act-runner
