---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner-secret
  namespace: act-runner
spec:
  encryptedData:
    REGISTRATION_TOKEN: AgAK1o8dGFw4YFy+dfcGd4f1XGsBUNj336UTiI7PpwUuX03iZe8M+udfX9lMC9YrEcnrFGytydqd0fF8ApJ9MVcAGw6/Yh9x9qy7gdU8oGs7Ot1G5XRu4Ty8uFovRMdwgqRUVI4IJgnLRFZDlxmaERpRMD4LQU8SYzIXo5ezAEBM/4jxrDmvvtv4EViaAI5TYOfrXxC55AvKoBUHGqT8PG+0zycPVThSNIVqs0uMiIRqJHFBlMRG//aylRUTtTiFGIiIdWrpNuy1755pjCgkaqF+6wH/aqc3Uu0MKiMEKNvs8nac20fdSydLk5RgMkWpJHfHn8M7kZh7pS83Q7kTIL2JLlYwL2oskSVXAfrSKx1sg+nXF92Z6l3JK/wLCuLdruD3bp2+JJxGqzJF5hScchHjJ8c3xe+N7oHvHpTHKb9RJ2rw+on6HhuCjnnqRrCFUV6wF9Fy/WLJiwSy8kkJD6Plzmr5Om3EqIMLTp5g81OcoBnJEENKaH7okvkFt7gEeGCjQmDm0/hpxGudvdE5doIPdaFxqKLajZT0bdSmcB5/T++p45xYzVZDSO/+5sGdAZg/Nv8XYG9RHhBwczZcbwg/bMRR0iU4kFCFmKgtVSd1JgM0eV2jOWW0v9fbC1xuVCp+nO+9AOIDD7H0mRZmguq5vJmXV6YPsxg4Uhb4pan1TjxA4zG4b3CdjAEnT+iDw0FgsqGKGYG1MmDMG5I3LhuN5iFp7IlxjuPiW6hU1zkVYNgEndv1ZUqICEQz
  template:
    metadata:
      creationTimestamp: null
      name: act-runner-secret
      namespace: act-runner
