---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-discord-secret
  namespace: hermes
spec:
  encryptedData:
    DISCORD_ALLOWED_USERS: AgBZPx8guJZkg9pEuaARxSH6dySWZ9Ej2uTZYyLqfCqzn/dT8fyZGvEd7AZ3s5OG6evfxeDOjc9BSyyxvo1AZVtUZhScxMOJV/Q7QRm0o3VY7wyciSOiykLRYOvw0SktbaGb2Q77GyGHFxn51S+Am0NsUqUFHaBthvkHPNDvo6uQVG7jYT0ehvhG2lOCQZIu5ETWBg/HU5Hli8gPcoDrBOEt/nHd5JyyZlJ08eFHWzel0Lj6b3cVxRclMCSaT2ebehbJzSoBRnspoAUkgIRsokkFWGue3t092VQJEmokotm4fu97wS3/2R0w2YS4MpqUxbjlnxDHyuMw8uGsx2WK7liS3TEyNU7w6JmWZB8EVFpxROmEvmtNNoSakh1GgLLxmPHdeyxHA+lqBALRSlubMRuRsQ5GJlnNHqARmexhBzFFpgM8CpW/NZHXN3Z3HP88g5uC71mGax30cIohz+UodKdk8S5bS2YEoAh9mnV3E/tliF4ZxWq90iGmTnYbKiCBJtrRL/20Vc0ptg4J6o7FvqxbDgG8O5+ulResGFi7rjae07ByikVqfsmqmdWfVZQyWUc6V8yiVktRa3+Vn4Vswcsqx5NwAFhEv23CaUNQKuFZ3g+ow4PPjVWkJzhvGrujRpAiquwqartmXTrEd4j1J0rkUpu32X507phRnd8lIhFr/OOArIUBd6FBe3vOUoE1HKX8ynzo+6c41xAYVGn9Ev9OZes=
    DISCORD_BOT_TOKEN: AgAjuug0H4vKglGf/GyiGPCdqtOZUQOIR/C3TiAxBhuG16DUBfaJOsqxOv1lf0jbgEIM8p7btTDvmD3hvhwtqBQ/jNXU/Fgwb8EEZfjxpJhae06XK/fs+knZ6wNOenzbr4Q3iQM+zZoyTLkhdweuD0Jr4+IayaxESUwl/elvEJX/sI5NYTIEeZQoSLKxth5iX5zG03veyuXBiPE+xkbe57yRBX0nq5FygMMwJqt5QAGIJtBu4HGYiOxjTBldzknn+oOgIoHlJQbuBvnhw+7Ow3RKXrPqesZpT8MvsQZoAVyMK4UP8+Xgr3ohq9Ctlc6pnhi0fawiwcZN+h2Mn3PP5HFwgvheEPm5alUL4Nq8mrm2MVNthf3lNXk8WP81ZgNMYChrkjQA7aVzu9lYkOSRuwTrlN7GldDDC4Aeqhr/oRjgsH+Z0G1DdVbdFeXf99Ofd5f4w7YMFhpAs8FupoDi7RdcbEx7Nq92Ga4oYzbVYLxXAo2QycZgiWV9SA+kBBwoiQMDKnpuOawz8iIIUSS+U2zKIX/I2+l3tNK8q0qYSx7JgCGDle+wFbFEcIpLFPBHQucu6DBOY7mDrq/yx1Sc9Bbb3vLDymc3+1ccciJGUDFkNR2a6S737b6lerSNTq+HlDycno9nQzi1NC2Z03c+dIBSk+yENlwxXN2SGj93o8bWnJe1gEc9i+07AgfrVh44q3CLD1gjYNZdD9s78nn31BlHGwUTdb5iHcAW9hc2xJUOblU1vrzBq7Z3PZ16VWsQ4cmDo0x51FgeJMckuAj3+JyJNaRBvdRd9sw=
  template:
    metadata:
      creationTimestamp: null
      name: hermes-discord-secret
      namespace: hermes
