---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-model-secret
  namespace: hermes
spec:
  encryptedData:
    OPENCODE_GO_API_KEY: AgARaM3z6Lb5K9J1+QiGUageEdULPEJGgedGPTvQPMKc+l0puFUkxgRPbRwECEapcfcrA6QZX/v1UAC+XHmcwxDU6JUEOeKmqzEpJ/Ootfqj7EvzHN/ggnnenL4tfz2DEbq7v+yibNB6EmB2HFxFE2hA4t26bVAYLVCz4Ccm6be7YGLbeB0fjt+i4t0vhvKgw4pJd5lvXn3j5m9eAlpn+bBFSuh8iFUFM1Oh2GfhRz4P0IVCwy7q2maixcYxXBk1l3YWVjKkzxBvF03ZyZqlDZqqaw1pn0beDI6E7w+2psqHyGrOUofK50ic4aex5C3blFtl/j1KWXh5guCwVb3tZLZBM5xrPbWUgipTj+zOIN0XKexmFwayB/pnfxlLVtinGozr9xmBM8IyoJ5nJeuwU+kuMuXS+YMfjxasq6oNqp3kYTVIT/KjP2oGAfzVd7oZrwX/Sq4NmwYKsIIUaNyefJ1JlEiGN71y9daT1nqdZf3PdJn8JpRWOhrZ8G7tL6Mtm/8h2kJjPcu0djTBVKwnf6VwScBWhvwWsoBqeR73kfVPXZphJqbCjUCDoJ6LdIknf3smF6tAwUCkB2HXyy9Ya2JD+wFtozeQN0mF4956lCAk8OVKwwj2RVkWuuJxiu6xxuDIDiwio/TeSk+AMSFHuFLYNfZaOnN1jQ5HVCIkGi6IGp3E1mzGVbisIwz2NGvwkQqclO6FRquvb5ZJAsYjdahvOQ3Jp9vgbJpM+ZzNAPaQU9hUBUPdTUCsHGl8joPEXbvL1KMWe1PEFT0Of/6+uwDLflTa
  template:
    metadata:
      creationTimestamp: null
      name: hermes-model-secret
      namespace: hermes
