---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-api-secret
  namespace: hermes
spec:
  encryptedData:
    API_SERVER_KEY: AgCFT4dQi5im0zKdf685E7L8m/yEAAfKqJCHZHPrjOsG50seEJDmSl7hIaj286AWzVvbDxBDJExbSUhCMRwkKwJWtCANY4ebPaLPqG9QZ493dsNTSXO6+dGsrffra05OCi6g9UfyLNT9/zPK3jEMddcSG+3euYOtE32s+w8xDqa/51HnVRHFD/SbvP0T4RJCH5P0IUZLkCo24W+8qlF1VFKAk9rMETVWRPBtIfnnQVdvlRnS+HRgDU/Q3TxOkpjEtJ9p4kxifOn7h9QvKbB8Z9i7PVEFyWgtCdMqNt8fFoQg8zfH3Pgp1wyNGBKmNo9QWbePjkCHazYik+4dcv9aKmPP6WsybQwEWZrf3hr4NZ/bpQc19tuCmC9c1VsEsY+/0Xg2MPV7OrcEtO9fnuqhOld0H/Awe4anGX/IC6Q1dl+G1eD0HfsodZnX3lbpJzdMjuH8mrwHsY8gN/N4FqAqsiI16xcQGn8VSwx1jFS0TgJV/VvR+pRNwVp2prT+38v6kN/M4kDCW5hx+zBYd4b6WC5latEaV4oW+kcefmToonZUOQiT3414FPhS0ca84dzLMTT4D5JsgFish++s9nWUUnLQLLjm23fSvqeCNjjmHd4dq/aWSbSolkRVBIiQiTKcsz55gH8E223zMTePAx7wHpJkLiBZiu8fZH60qwfGMt+xUFLfMfPIdnD5J2ZZUmCtkslD61d1fSKqtRHaRM8BBipc5FBPrCiSdUHK6AMSuI2paMYuPwGfa4uBOvBaSeKovWeqDo5GxPZj3oekdQCKx5g+
  template:
    metadata:
      creationTimestamp: null
      name: hermes-api-secret
      namespace: hermes
