---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-discord-secret
  namespace: hermes
spec:
  encryptedData:
    DISCORD_ALLOWED_USERS: AgBzjl2f5dJuDkmWd4Z+tbAMXn8Knu6gEj87Whg1oQfQ0UAOHysTD003oG3LCUi20oYfBAwSQ9CqBOq972kpLMsDAJSucImuQW+Vm9y3dpG6DF2xhmp/v7sWYjTgwyOryHi6X3C9gd0yn3IRz0KASD+n4DcTygx+YmmyHHeUaexQN5xG4wDWN8TeyXGK7Dvu9tdFYhLMdoymXOatkvBYSX6uhH2p1sIJF7uVlhBkG3FuiBkSu/gX9YUL9kbCOMWIiyIT2eY57hohzL0IrdhIwb4jvEMO1+6hSGpr6RWUeAu7encAFRNU9iadq0OQLR8c8ZYjQPhXiTlPmGVvMCZGf7eM+kYrV972WMCfnzOloF+9hHFBgvyJmXUsdYOE+kV7RVLXYJ0ZfpzHNCZEsAKv8433R9gF6wfTY0n3X6zRbaMvUkgEXLHHlv5/gd7mOlvMPmG0z1eyqULEToPgcoK7tkOXyChb/fVlS8UqqPdwDJUdwnp69jgRaZJOD4AddmcDVgkzHKoasetjTguse5K9+urKqDYAHimVGX5pL6uF3yeXpcuDsJT+2GpNDPYPeL53Hg1Pe8/4ve6oAtRxyxubB2F/ANn+asTXhDEQjxzsrsCd5GdBeWWnv3SW95Xmc+EepiMljxpZd1THWWkKdCC+SipL5EmUnfuaq3fGONFhlDNR2hNFIGq5axONX85+4ZkjQdXtiwu6FKPj1mKyCq3SGLE+iQuy1slbeeBNJUHIkZ1vjcGazP1C
    DISCORD_BOT_TOKEN: AgAcw/RQ2/4KhFisvdHotJ2jG4Mb9FMZv0LoURluR/WLeLw3YdZHI0QtC+kDlWXi8qfUsC0Jtz1BTQi362/1izgMJDYo6MHZy/TPfCjvsAdGOZ2T6HgSXIu27cJ/0Xlt/b84LIrZXidUoamhks658tgh6cwlRxXBAuLS/Fi3VJQFmWKQKtDh65sv7ejoo0mG1fndyUOY31LXWmQhBPc0y89boVs01HNfKCkZl4/keTMnXfU2IW/fghqVqjFCRUHuPEoGiuBIG9hVauRmToVH+AUi8LpsACkF1U/dSI5rjhKCN2FLw9JLtQlcTWSHcKdtRK0N1QU38ucLB7lP0FWxsEliVUMW2Ho6PSOjkIKpNVK3fjx1OyOBDkcQH/Rv74qhwqDF9t/HyoAt/7Viagzy5bBwUaANJcqUgaUbnfnwyOY3OJElwBWCoHvH1igkzWrSU8d7MASgYazseKWhYTw5FkwyYgM8KRz71FzYkkyGHhUHYSnbUjyBO9M+/FVy66NBqvWJe8+xpY2qimAuLuFFcGsE0ryojH0o5NSTQRWNkfgZT6/6LnuyH7EqgvqX9V8pxlZPFJYAXqolF2nFafXtRIfmPa5cMA5Epr9mkAX70TD8jz/7C02FOorR1rmzRKDBTdKVY1v/i7cRL/B/iHDDJbPG0uWYnlteai8ZY4uvST/uBTpn25G82FDYrU4xzG/SzYCNcC/iLou/Gu7tssOWzVQZFpMKoZZlMXaZe0iy54v+nC0TP+KH+oXKa8Y6ZOYS+aFf+NLF/u03gKS/wyjs2ZZWcbHI3zMWhaA=
  template:
    metadata:
      creationTimestamp: null
      name: hermes-discord-secret
      namespace: hermes
