---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-discord-secret
  namespace: hermes
spec:
  encryptedData:
    DISCORD_ALLOWED_USERS: AgAHyY/7yK5+skHpX3DJ73iHpCFKja118awVj1vLDa4EJZD9jit712SAYdLbF11wqG8Ck2yUuCFkr5IlZRnr1dztiojoMzuc9aWOMKbkZyzXkUhKJduQ8qohDZL1CzIXbVY+y5OrI/5/ZFp63074p5h17pvat8l0w0WPQacUmRu7RCR8fwWZWQYltmSCf7mrGGQE/xcXHTchaD1/PAoQqsPWJd0303u6Qbazo04Y0zYiGarjXoTyt74CrD8+jip9RQ3DKU8ElRays5NshqRa42i1/Hi2EofP1MS6IQY6zL41M/d72MRy8P3rODQQ3Cb5L5lnLBSppb9avcj0DoZUCeS06Apa3Qjxgf+t1WNDWCfiWcKULJ5lcFBRwanoB7K5L27KmSF764M+V6eD28AgD4NcEmAucKacKRlq1jOPTUV7/iDwOBMFc/v3HK5yVgzkZasDrx7MbBojK1YCe64bMtBcMtQqaon7cE7PeN6cIJnGtE3iRNAMykgBaXX0es4KMzFC28vKnWMI7gl7PyTfr3KgJHrZJ2pEuyjJ8XGQkANi5SBwqgWJNvdfLfZNn4MtIi3o9ihZgqtPf/gRsp6F4g5IHrmwde03bihv8v2CvPKWmfhzy+lHcOMGUR0PCT92i/Gf7HvJsWxEbuV+MW/b/KsOiuJRqNm81eicQgB+TLtOvKSw9Ex1ia4TfI1US61H82XctVTd7HzPxZGaZlzp9ldCnwhJDks0FmxG+4WnocWN6lyZd83nZQNBg8p4MuRqSnab7WT/OKMe+AE=
    DISCORD_BOT_TOKEN: AgAcw/RQ2/4KhFisvdHotJ2jG4Mb9FMZv0LoURluR/WLeLw3YdZHI0QtC+kDlWXi8qfUsC0Jtz1BTQi362/1izgMJDYo6MHZy/TPfCjvsAdGOZ2T6HgSXIu27cJ/0Xlt/b84LIrZXidUoamhks658tgh6cwlRxXBAuLS/Fi3VJQFmWKQKtDh65sv7ejoo0mG1fndyUOY31LXWmQhBPc0y89boVs01HNfKCkZl4/keTMnXfU2IW/fghqVqjFCRUHuPEoGiuBIG9hVauRmToVH+AUi8LpsACkF1U/dSI5rjhKCN2FLw9JLtQlcTWSHcKdtRK0N1QU38ucLB7lP0FWxsEliVUMW2Ho6PSOjkIKpNVK3fjx1OyOBDkcQH/Rv74qhwqDF9t/HyoAt/7Viagzy5bBwUaANJcqUgaUbnfnwyOY3OJElwBWCoHvH1igkzWrSU8d7MASgYazseKWhYTw5FkwyYgM8KRz71FzYkkyGHhUHYSnbUjyBO9M+/FVy66NBqvWJe8+xpY2qimAuLuFFcGsE0ryojH0o5NSTQRWNkfgZT6/6LnuyH7EqgvqX9V8pxlZPFJYAXqolF2nFafXtRIfmPa5cMA5Epr9mkAX70TD8jz/7C02FOorR1rmzRKDBTdKVY1v/i7cRL/B/iHDDJbPG0uWYnlteai8ZY4uvST/uBTpn25G82FDYrU4xzG/SzYCNcC/iLou/Gu7tssOWzVQZFpMKoZZlMXaZe0iy54v+nC0TP+KH+oXKa8Y6ZOYS+aFf+NLF/u03gKS/wyjs2ZZWcbHI3zMWhaA=
  template:
    metadata:
      creationTimestamp: null
      name: hermes-discord-secret
      namespace: hermes
