---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-registry-secret
  namespace: hermes
spec:
  encryptedData:
    .dockerconfigjson: AgCSkZhzoEd4uUObh5m4LXNEgyVIg0HMpmBFMHEAg+MjruRyWowE2cS9gGyoyxHq5QS1q7Nt00KSAe2uWlFtE5b+jMHSse7rsc5IvZ694zOaCGUGILiXC4sQV+7zSUrj5L1ISbK6RZfoMS/st9KV8oUbq3yK0m7Mr7RNzSwFt5DregMv6OS+b6CBybwXlNBnn+ak/C1C+nhKw3/Zh9zD4Mvdz+cZS+zLZv5pT4UtCHafcC35p7WtwNfGxyO04GRrv5+lHd0f4feMfad+fulDSdL4T97APNEFCXDPi+hVs2fse/j+xS2BE4dHRH5Yf0OOkeA4cYtGeZCAqxJ5RD/La/OmIMWubHYt5yQvXa1hRw5huui1jb/FeCXFvgnv84ZR4t95aprwVXsD4o/hbHri8jufMAlagb1fMzE9alJNbGk4Pg9y/sedXu5z9CoNUpsR7qwj4LR8EKXrSpsLSqRdGxvBivuRx3YhzIokY/BhYTvkSwf4v6ty2SGoJYZzebC3tDnado/DjSI+aJkbhTSyoPat2Tgtkn3oKthD9REzK9yE8Nwx3cdSdbrAMabjZRV7/eelta2UJKkJ0Dt0lIL7C3OrKJ2+19t+YZH20RfsETMUFmttPwHjWPo4fb2SUuoJY5EGxfzBSDrVmqemO8hbvsrmOxn7qpUpL14+dsfZEZj4waPbrluG6gKdV0Y+a9oATMId/AL+8jrkWfZXyvuwWcyVVe5zQtZ0gs5Gb1O/rZ0yj+HdaJ4KV83ZEVMpdBDB1dG13+8j7v5egV9Dk6WYaFOfEzpO4s4NmFOMfnibjEKpO4GHd8beUEwLMG7spF0L+rVstnp/FtdscJF5K+EltZ2+u1MjL8JeJ6pUiIWYao6ynu04rQg+B5Lt1bcS8RDBPXT9s/Twx6+sLQ5cty7OCZ8xhoxFuZgotWka04GYBRlopJgnOhKRiQ==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-registry-secret
      namespace: hermes
    type: kubernetes.io/dockerconfigjson
