apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn-helmrepo.yaml
  - longhorn-helmrelease.yaml
  - mojo2600-helmrepo.yaml
  - sealed-secrets-helmrepo.yaml
  - sealed-secrets-helmrelease.yaml
  - forgejo-helmrepo.yaml
  - n8n-helmrepo.yaml
  - prometheus-helmrepo.yaml
  - grafana-helmrepo.yaml
  - tailscale-helmrepo.yaml
