apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-values
  namespace: pihole
data:
  values.yaml: |
    persistentVolumeClaim:
      enabled: true
      storageClass: longhorn

    serviceDns:
      type: LoadBalancer

    serviceWeb:
      type: ClusterIP

    ingress:
      enabled: true
      hosts:
        - pihole.lan

    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 1.1.1.1

    customDnsEntries:
      - address=/pihole.lan/192.168.1.205
      - address=/forgejo.lan/192.168.1.205
      - address=/n8n.lan/192.168.1.205
      - address=/prometheus.lan/192.168.1.205
      - address=/grafana.lan/192.168.1.205
      - address=/plan-assistant.lan/192.168.1.205
      - address=/cycling.kvarnberg.labs/192.168.1.205

    admin:
      existingSecret: pihole-admin-secret
      passwordKey: password

    monitoring:
      sidecar:
        enabled: true
