apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-tailscale
  namespace: pihole
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: pihole-web
      port:
        number: 80
  tls:
    - hosts:
        - pihole
