apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-values
  namespace: forgejo

data:
  values.yaml: |
    gitea:
      admin:
        username: johan
      config:
        indexer:
          REPO_INDEXER_ENABLED: true
        metrics:
          ENABLED: true

    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi

    ingress:
      enabled: true
      hosts:
        - host: forgejo.lan
          paths:
            - path: /
              pathType: Prefix
