---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-secret-values
  namespace: forgejo
spec:
  encryptedData:
    values.yaml: AgAv33gDNyFIvrbuDyQpHVR/LJqCYTqFwOsDx+ewhiUF0uGgANfGixKaZeWKHZdQ9hhxYJ56cERhjfFgAyshgCRTLeF+406fJwFqg9fzKcI1Yd1BzX4bd+SiilB7fdtRBs+ZS7vjscc18qyCD1R9iFUE7yFnTjjmj3GMInl7vrdoW7WjjMZZka8n5ucP/LspoHwrVUAKdsC5pXQkVKRuVjEHRTLQpnFlVKuqRuS3EDvf0gvz6pBPqWtxS33NrYfKwbLdLnaZbBlP+LoiJmdHhJPr7nTF7PaVIl/4HBLRErBRFTKhiEPYgdlMzzFCBJSU/VDqjaBuocXTx5t6jCfSjGqu43SXCuZyL9NTEyO1bcLMByPI5Oiyd98n6AnVBCPerI61YcD25NJaht4HGW/FyX+uRNd8OfylFR5uz52gRHqhvN+Og/n2w3k02NyhyaN2aFUGLlVfp+5UhKRIkRzIsr6K+w89gpk5V2ebWE+792sxZ+U/Vlg1aA+oxQfhUIBiKjFNvQQv8fWo8t/DROV2f10nwl3j8YgPy1ih0dKTsqELLvIC/zddfauBNa0t5VE2VRiahXGWnd4Je41h7sGBfRUwbnwkAp7rPr5u+Eszu9pcQ7TxR7TqRRLkpzLU/phufCY+MB731pwHW6x8uuQyjyTpN0FF4PPxWu3BUn01xs9yZE9duatb8/sbsnePODTV4lcwuD4qNt0+WHnsRktnLEGHAJ4DaQYdkGlxpxGFi0/u067ANtRkZWH4
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-secret-values
      namespace: forgejo
