apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana-helmrelease.yaml
  - grafana-values.yaml
  - grafana-sealed-secret.yaml
  - tailscale-ingress.yaml
  - ./dashboards
