apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - frontend-nginx-configmap.yaml
  - postgres-statefulset.yaml
  - services.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - tailscale-ingress.yaml
  - plan-assistant-sealed-secret.yaml
  - registry-sealed-secret.yaml
