apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cycling-training-app-data
  namespace: cycling-training-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
