---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-registry-secret
  namespace: cycling-training-app
spec:
  encryptedData:
    .dockerconfigjson: AgAYtCOf5FkrwbKIgeNhF9zH2sRZyU04CyPw9IkoCarrT0wr8zZzBGpq0UY9iaafzfrLuMMdOMpE0bqdH781jk4jaSRHsoh1/Hx3+3Z0rAAzot0w0OjnzyD1Pw+Fg1QD4uBlKdJSOiEOgE/uSf5L77McXVz2OmFEht4/L6x0hN6Ulrx3Eni5UCZ7hWqawqY5PvrbGBk4Rh+Js6OKFk0pWy/61SspI5OceUTpIjEcz2+aQqAe+EKYnrHOP1v8ithBqs8hcP6znGsgO3sn73wrvOBHRNB8HHfHnFuvN71wnXUdzjOxAl+/vIjY3JtrXE2A9MNnZX3ypGF473Z9loFF304qKRCyBXBDsYxJtP2lPNBctOfo+4e19CSe5h/NYjxKlfmFhFELQHmBX5JTh9hLtlzIzcEOm4ke7IL5wpxdgAoZ5dE/96o/lVek/6UafugodXfZ83Gel6kNTlkxx5uCaANm8qb2dkZ3Jyg01vv3MYquFty0d9dtxv1mXma8V82GBlIfrIE3aL8gAZVfGRfefpCkiZG8dEKoLFCAtQuH/3kd51gLFiU47rNVXoDt/slh84eSX6lExIP+V9GmVVaIkh/6Azi+rSx1oRh4A8DjpZ1xGylSKcNTv/RFZbpRqphpgu09ft02TE2e+BfsAU84v86mrPawT6OqseOVtqvIm4sj922rxkuIwPNF6xkj+t9cGnWRWmCEzOM6Sha5MZedkYqNIWzozcfFt5Na5ENMjyRp7Z+RdjS+SFgDwmx7holMt1d5PtlCH6u735nrzNjXgcfrg3qt/WBDNOs2Ih5B68eWmWQoITTo+h4++6BnQNNXLKvOV1eisr+X+04XqYpEOnxe
  template:
    metadata:
      creationTimestamp: null
      labels:
        kustomize.toolkit.fluxcd.io/name: apps
        kustomize.toolkit.fluxcd.io/namespace: flux-system
      name: forgejo-registry-secret
      namespace: cycling-training-app
    type: kubernetes.io/dockerconfigjson
